# Initial cache for a CIR-enabled LLVM build containing circc as an external
# project. Invoke this file with `cmake -C cmake/caches/LLVM.cmake ...`.

get_filename_component(CIRCC_SOURCE_DIR
  "${CMAKE_CURRENT_LIST_DIR}/../.."
  ABSOLUTE
)

set(CMAKE_BUILD_TYPE Release CACHE STRING "")
include("${CMAKE_CURRENT_LIST_DIR}/../toolchains/Clang.cmake")

if(CMAKE_HOST_WIN32)
  set(CIRCC_PYTHON "$ENV{CONDA_PREFIX}/python.exe")
else()
  set(CIRCC_PYTHON "$ENV{CONDA_PREFIX}/bin/python")
endif()
set(Python3_EXECUTABLE "${CIRCC_PYTHON}" CACHE FILEPATH "" FORCE)

find_program(CIRCC_SCCACHE_PROGRAM
  NAMES sccache
  HINTS "$ENV{CONDA_PREFIX}/bin"
  REQUIRED
)
set(CMAKE_C_COMPILER_LAUNCHER "${CIRCC_SCCACHE_PROGRAM}" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER_LAUNCHER "${CIRCC_SCCACHE_PROGRAM}" CACHE FILEPATH "")

set(LLVM_USE_LINKER lld CACHE STRING "")
set(LLVM_ENABLE_ASSERTIONS ON CACHE BOOL "")
set(LLVM_ENABLE_PROJECTS "clang;mlir;lld" CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD host CACHE STRING "")
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "")
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "")
set(LLVM_INCLUDE_DOCS OFF CACHE BOOL "")

set(CLANG_ENABLE_CIR ON CACHE BOOL "")

set(LLVM_EXTERNAL_PROJECTS circc CACHE STRING "")
set(LLVM_EXTERNAL_CIRCC_SOURCE_DIR "${CIRCC_SOURCE_DIR}" CACHE PATH "")
